In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.svm import SVC
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['flower']  =iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[48:53]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   

        flower  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor  
52  versicolor

In [3]:
X_train, X_test,y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [4]:
model = SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.8888888888888888

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
cross_val_score(SVC(kernel='linear',C=10, gamma='auto'),iris.data,iris.target)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [7]:
cross_val_score(SVC(kernel='rbf',C=10, gamma='auto'),iris.data,iris.target)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
cross_val_score(SVC(kernel='rbf',C=20, gamma='auto'),iris.data,iris.target)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [9]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval, gamma='auto'),iris.data,iris.target)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)
    
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [10]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel': ['rbf','linear']
})

In [11]:
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.0042419 , 0.00504198, 0.00356698, 0.00248356, 0.00240073,
        0.00246811]),
 'std_fit_time': array([0.00068574, 0.00310067, 0.00090325, 0.00048598, 0.0006946 ,
        0.00040528]),
 'mean_score_time': array([0.00620232, 0.00253816, 0.00227804, 0.00179467, 0.0022707 ,
        0.00254178]),
 'std_score_time': array([0.00666354, 0.0005887 , 0.00045018, 0.00047368, 0.00040992,
        0.00102071]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': ar

In [12]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.004242      0.000686         0.006202        0.006664        1   
1       0.005042      0.003101         0.002538        0.000589        1   
2       0.003567      0.000903         0.002278        0.000450       10   
3       0.002484      0.000486         0.001795        0.000474       10   
4       0.002401      0.000695         0.002271        0.000410       20   
5       0.002468      0.000405         0.002542        0.001021       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [13]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [14]:
clf.best_score_

0.9800000000000001

In [15]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [16]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'),{
    'C' : [1,10,20],
    'kernel': ['rbf','linear']
},n_iter=2)

In [17]:
rs.fit(X_train,y_train)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf         0.971429
1       10       linear         0.952381